; General Tiles
GLOBAL Blocks
GLOBAL Barril
GLOBAL Pipe_head
GLOBAL Pipe_body
GLOBAL Pipe_link
GLOBAL Floor

; Enemy 1
GLOBAL Enemy_1
GLOBAL Enemy_1_Attack
GLOBAL Enemy_1_Blink
GLOBAL Enemy_1_Explosion

; Enemy 2
GLOBAL Enemy2
GLOBAL Enemy2_1
GLOBAL Enemy2_2

; Bullet
GLOBAL Bullet

; General Tiles (tiles 0-4)
BARRIL_TILE         EQU 0
PIPE_HEAD_TILE      EQU 1
PIPE_BODY_TILE      EQU 2
PIPE_LINK_TILE      EQU 3
FLOOR_TILE          EQU 4

; Enemy 1 (tiles 5-7)
ENEMY1_ATTACK_TILE  EQU 5
ENEMY1_BLINK_TILE   EQU 6
ENEMY1_EXPLODE_TILE EQU 7

; Enemy 2 (tiles 8-9) - (8x16)
ENEMY2_1_TILE       EQU 8   ; Primer frame (2 tiles)
ENEMY2_2_TILE       EQU 10  ; Segundo frame (2 tiles)

; Bullet (tile 12)
BULLET_TILE         EQU 12

; End of SPRITES.INC
